name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [  ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 12
        
    - name: Install hexo
      run: |
        npm -g install hexo
        npm install
      id: install

    - name: Build blog
      run: hexo deploy
      id: build
    
    - name: Deploy blog to pages
      id: deploy
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        allow_empty_commit: false
        build_dir: ./public
      
